# Generated by Django 2.1.5 on 2019-01-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190124_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caleg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_urut', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dapil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dapil', models.CharField(max_length=50)),
                ('daerah_dapil', models.IntegerField()),
                ('provinsi', models.CharField(max_length=50)),
                ('kota', models.CharField(max_length=50)),
                ('kab', models.CharField(max_length=50)),
                ('kec', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriCaleg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_partai', models.CharField(max_length=45)),
                ('kode_partai', models.IntegerField()),
                ('gambar_partai', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('ttl', models.CharField(max_length=60)),
                ('no_telp', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='accesrecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='category',
        ),
        migrations.DeleteModel(
            name='AccesRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
        migrations.AddField(
            model_name='caleg',
            name='dapil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dapil'),
        ),
        migrations.AddField(
            model_name='caleg',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.KategoriCaleg'),
        ),
        migrations.AddField(
            model_name='caleg',
            name='partai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Partai'),
        ),
    ]
